const WORD_POOL = [
  'time', 'year', 'people', 'way', 'day', 'man', 'thing', 'woman', 'life', 'child',
  'world', 'school', 'state', 'family', 'student', 'group', 'country', 'problem', 'hand', 'part',
  'place', 'case', 'week', 'company', 'system', 'program', 'question', 'work', 'government', 'number',
  'night', 'point', 'home', 'water', 'room', 'mother', 'area', 'money', 'story', 'fact',
  'month', 'lot', 'right', 'study', 'book', 'eye', 'job', 'word', 'business', 'issue',
  'side', 'kind', 'head', 'house', 'service', 'friend', 'father', 'power', 'hour', 'game',
  'line', 'end', 'member', 'law', 'car', 'city', 'community', 'name', 'president', 'team',
  'minute', 'idea', 'kid', 'body', 'information', 'back', 'parent', 'face', 'others', 'level',
  'office', 'door', 'health', 'person', 'art', 'war', 'history', 'party', 'result', 'change',
  'morning', 'reason', 'research', 'girl', 'guy', 'moment', 'air', 'teacher', 'force', 'education',
  'foot', 'boy', 'age', 'policy', 'process', 'music', 'market', 'sense', 'nation', 'plan',
  'college', 'interest', 'death', 'experience', 'effect', 'car', 'thing', 'girl', 'boy', 'food',
  'sun', 'tree', 'farm', 'bird', 'dog', 'color', 'bank', 'fish', 'road', 'cat',
  'horse', 'mountain', 'computer', 'ocean', 'train', 'ship', 'plane', 'gold', 'pizza', 'cow',
  'radio', 'planet', 'flower', 'river', 'rock', 'sand', 'grass', 'star', 'earth', 'forest',
  'hair', 'snow', 'tree', 'rain', 'sea', 'lake', 'moon', 'cloud', 'park', 'plant',
  'desert', 'street', 'wind', 'port', 'storm', 'garden', 'valley', 'hill', 'kitchen', 'diamond',
  'sound', 'village', 'ice', 'island', 'beach', 'egg', 'fire', 'bridge', 'paper', 'frog',
  'duck', 'whale', 'shark', 'tiger', 'lion', 'elephant', 'giraffe', 'monkey', 'kangaroo', 'penguin',
  'dolphin', 'owl', 'eagle', 'butterfly', 'bee', 'spider', 'ant', 'deer', 'bear', 'wolf',
  'fox', 'rabbit', 'squirrel', 'mouse', 'snake', 'crocodile', 'octopus', 'pig', 'goat', 'sheep',
  'chicken', 'turkey', 'duck', 'goose', 'peacock', 'parrot', 'flamingo', 'swan', 'seagull', 'pigeon',
  'apple', 'banana', 'orange', 'grape', 'lemon', 'strawberry', 'peach', 'pear', 'pineapple', 'watermelon',
  'cherry', 'blueberry', 'raspberry', 'blackberry', 'mango', 'coconut', 'avocado', 'kiwi', 'pomegranate', 'fig',
  'potato', 'tomato', 'carrot', 'onion', 'garlic', 'lettuce', 'cucumber', 'pepper', 'broccoli', 'corn',
  'pea', 'bean', 'mushroom', 'pumpkin', 'squash', 'eggplant', 'cabbage', 'celery', 'asparagus', 'radish',
  'bread', 'cheese', 'butter', 'yogurt', 'milk', 'cream', 'ice cream', 'chocolate', 'candy', 'sugar',
  'salt', 'pepper', 'oil', 'vinegar', 'sauce', 'soup', 'salad', 'sandwich', 'pizza', 'pasta',
  'rice', 'noodle', 'meat', 'beef', 'pork', 'chicken', 'fish', 'shrimp', 'crab', 'lobster',
  'oyster', 'clam', 'mussel', 'squid', 'octopus', 'sushi', 'taco', 'burrito', 'hamburger', 'hotdog',
  'shirt', 'pants', 'dress', 'skirt', 'jacket', 'coat', 'sweater', 'sock', 'shoe', 'boot',
  'hat', 'glove', 'scarf', 'tie', 'belt', 'button', 'zipper', 'pocket', 'umbrella', 'glasses',
  'watch', 'ring', 'necklace', 'bracelet', 'earring', 'wallet', 'purse', 'bag', 'suitcase', 'backpack',
  'pen', 'pencil', 'marker', 'crayon', 'paintbrush', 'canvas', 'easel', 'palette', 'sculpture', 'pottery',
  'guitar', 'piano', 'violin', 'drum', 'flute', 'trumpet', 'saxophone', 'harmonica', 'harp', 'banjo',
  'football', 'basketball', 'baseball', 'tennis', 'golf', 'soccer', 'volleyball', 'rugby', 'cricket', 'hockey',
  'skateboard', 'bicycle', 'motorcycle', 'car', 'truck', 'bus', 'train', 'airplane', 'helicopter', 'rocket',
  'boat', 'ship', 'submarine', 'spaceship', 'telescope', 'microscope', 'camera', 'television', 'radio', 'telephone',
  'computer', 'laptop', 'tablet', 'smartphone', 'keyboard', 'mouse', 'printer', 'scanner', 'projector', 'speaker',
  'microphone', 'headphone', 'battery', 'charger', 'cable', 'wire', 'antenna', 'satellite', 'robot', 'drone',
  'clock', 'calendar', 'compass', 'map', 'globe', 'book', 'magazine', 'newspaper', 'letter', 'envelope',
  'stamp', 'postcard', 'card', 'ticket', 'passport', 'license', 'certificate', 'contract', 'menu', 'recipe',
  'dictionary', 'encyclopedia', 'novel', 'poem', 'script', 'essay', 'report', 'diagram', 'chart', 'graph',
  'table', 'chair', 'desk', 'bed', 'couch', 'sofa', 'shelf', 'cabinet', 'drawer', 'mirror',
  'lamp', 'chandelier', 'candle', 'fireplace', 'stove', 'oven', 'refrigerator', 'freezer', 'dishwasher', 'washing machine',
  'dryer', 'vacuum', 'broom', 'mop', 'bucket', 'sponge', 'soap', 'towel', 'blanket', 'pillow',
  'curtain', 'rug', 'carpet', 'tile', 'brick', 'concrete', 'wood', 'metal', 'plastic', 'glass',
  'rubber', 'leather', 'cotton', 'silk', 'wool', 'paper', 'cardboard', 'clay', 'wax', 'paint',
  'ink', 'glue', 'tape', 'string', 'rope', 'chain', 'wire', 'nail', 'screw', 'hammer',
  'screwdriver', 'wrench', 'pliers', 'scissors', 'knife', 'fork', 'spoon', 'plate', 'bowl', 'cup',
  'mug', 'glass', 'bottle', 'jar', 'can', 'box', 'basket', 'bin', 'trash', 'recycle'
];

export default WORD_POOL;